spring.application.name=urlshortner


# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/shortener-db


# Redis
spring.data.redis.host=local
spring.data.redis.port=port

# Enable scheduling
spring.main.allow-bean-definition-overriding=true

# (Optional) Mail config
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your_email@example.com
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


application.shorturl.dns=http://localhost:8080